name       : liteide
version    : '35.1'
release    : 13
source     :
    - https://github.com/visualfc/liteide/archive/x35.1.tar.gz : e50668af4786424c795b4ea15f098b9141338ea08eac47026d29e6913bcc51e9
license    : LGPL-2.1-or-later
component  : programming.ide
summary    : IDE for editing and building projects written in the Go programming language
description: |
    IDE for editing and building projects written in the Go programming language.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
rundeps    :
    - golang
setup      : |
    pushd liteidex
        %qmake . PREFIX=/usr
    popd
build      : |
    %make -C liteidex
install    : |
    %make_install -C liteidex INSTALL_ROOT=%installroot%

    install -dm 0755 $installdir/usr/share/liteide

    # some filenames contain whitespaces
    IFS=$'\n'
    pushd liteidex/deploy
    for file in $(find . -type f); do
        install -Dm00644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    pushd liteidex/os_deploy/linux
    for file in $(find . -type f); do
        install -Dm00644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    # remove static libraries
    rm -frv $installdir/usr/lib/liteide/*.a

    install -Dm00644 $pkgfiles/liteide.desktop $installdir/usr/share/applications/liteide.desktop
