name       : liteide
version    : 37.4
release    : 24
source     :
    - git|https://github.com/visualfc/liteide.git : x37.4
license    : LGPL-2.1-or-later
component  : programming.ide
summary    : IDE for editing and building projects written in the Go programming language
description: |
    IDE for editing and building projects written in the Go programming language.
networking : yes
builddeps  :
    - pkgconfig(Qt5WebKit)
    - golang
    - git
rundeps    :
    - golang
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-go-install.patch
build      : |
    cd $workdir/build
    export GOPATH=`$PWD`
    export QTDIR=/usr
    ./update_pkg.sh
    ./build_linux.sh
install    : |
    install -Dm00755 liteidex/liteide/bin/liteide -t $installdir/usr/bin

    install -dm00644 $installdir/usr/lib/liteide/plugins
    mv liteidex/liteide/lib/liteide/plugins/* $installdir/usr/lib/liteide/plugins/

    install -dm00644 $installdir/usr/lib/liteide
    mv  liteidex/liteide/lib/liteide/libliteapp.so* $installdir/usr/lib/liteide

    install -dm00755 $installdir/usr/share/liteide
    # some filenames contain whitespaces
    IFS=$'\n'
    pushd liteidex/deploy
    for file in $(find . -type f); do
        install -Dm00644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    pushd liteidex/os_deploy/linux
    for file in $(find . -type f); do
        install -Dm00644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    # remove static libraries
    rm -frv $installdir/usr/lib/liteide/*.a

    install -Dm00644 $pkgfiles/liteide.desktop $installdir/usr/share/applications/liteide.desktop
