name       : liteide
version    : '33.3'
release    : 8
source     :
    - https://github.com/visualfc/liteide/archive/x33.3.tar.gz : 31d9b1949f9d8a1027e669b8cca1cd274aa92db5fc3a97e2dd950763a85c1556
license    : LGPL-2.1
component  : programming.ide
summary    : IDE for editing and building projects written in the Go programming language
description: |
    IDE for editing and building projects written in the Go programming language
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
rundeps    :
    - golang
setup      : |
    pushd liteidex
    %qmake . PREFIX=/usr
    popd
build      : |
    pushd liteidex
    %make
    popd
install    : |
    pushd liteidex
    %make_install INSTALL_ROOT=%installroot%
    popd

    install -dm 0755 $installdir/usr/share/liteide

    # some filenames contain whitespaces
    IFS=$'\n'
    pushd liteidex/deploy
    for file in $(find . -type f); do
        install -D -m 0644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    pushd liteidex/os_deploy/linux
    for file in $(find . -type f); do
        install -D -m 644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    # remove static libraries
    rm -frv $installdir/usr/lib/liteide/*.a

    install -D -m 0644 $pkgfiles/liteide.desktop $installdir/usr/share/applications/liteide.desktop
