name       : liteide
version    : '34'
release    : 9
source     :
    - https://github.com/visualfc/liteide/archive/x34.tar.gz : a59f858b0867a70aa457ab997a9102b24e733a05f617844a900a07c606a94eb7
license    : LGPL-2.1-or-later
component  : programming.ide
summary    : IDE for editing and building projects written in the Go programming language
description: |
    IDE for editing and building projects written in the Go programming language
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
rundeps    :
    - golang
setup      : |
    pushd liteidex
    %qmake . PREFIX=/usr
    popd
build      : |
    pushd liteidex
    %make
    popd
install    : |
    pushd liteidex
    %make_install INSTALL_ROOT=%installroot%
    popd

    install -dm 0755 $installdir/usr/share/liteide

    # some filenames contain whitespaces
    IFS=$'\n'
    pushd liteidex/deploy
    for file in $(find . -type f); do
        install -D -m 0644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    pushd liteidex/os_deploy/linux
    for file in $(find . -type f); do
        install -D -m 644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    # remove static libraries
    rm -frv $installdir/usr/lib/liteide/*.a

    install -D -m 0644 $pkgfiles/liteide.desktop $installdir/usr/share/applications/liteide.desktop
