name       : liteide
version    : '36.2'
release    : 22
source     :
    - https://github.com/visualfc/liteide/archive/x36.2.tar.gz : 31e913346b6b135b6d9d78873179dde42957ed8e1df2c14b4eae199686451f03
license    : LGPL-2.1-or-later
component  : programming.ide
summary    : IDE for editing and building projects written in the Go programming language
description: |
    IDE for editing and building projects written in the Go programming language.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
rundeps    :
    - golang
setup      : |
    pushd liteidex
        %qmake . PREFIX=/usr
    popd
build      : |
    %make -C liteidex
install    : |
    %make_install -C liteidex INSTALL_ROOT=%installroot%

    install -dm00755 $installdir/usr/share/liteide

    # some filenames contain whitespaces
    IFS=$'\n'
    pushd liteidex/deploy
    for file in $(find . -type f); do
        install -Dm00644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    pushd liteidex/os_deploy/linux
    for file in $(find . -type f); do
        install -Dm00644 "${file}" "$installdir/usr/share/liteide/${file#source/}"
    done
    popd

    # remove static libraries
    rm -frv $installdir/usr/lib/liteide/*.a

    install -Dm00644 $pkgfiles/liteide.desktop $installdir/usr/share/applications/liteide.desktop
